// <auto-generated />
using System;
using Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entity.Migrations
{
    [DbContext(typeof(DocumentContext))]
    partial class DocumentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<int>("CreateUserId");

                    b.Property<int?>("CreatedUserUserId");

                    b.Property<string>("ReferenceId");

                    b.Property<int?>("TypeofDocumentId");

                    b.HasKey("DocumentId");

                    b.HasIndex("CreatedUserUserId");

                    b.HasIndex("TypeofDocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Entity.TypeofDocument", b =>
                {
                    b.Property<int>("TypeofDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("TypeofDocumentId");

                    b.ToTable("TypeofDocuments");
                });

            modelBuilder.Entity("Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName");

                    b.Property<int>("UserStatus");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entity.Document", b =>
                {
                    b.HasOne("Entity.User", "CreatedUser")
                        .WithMany("CreatedDocuments")
                        .HasForeignKey("CreatedUserUserId");

                    b.HasOne("Entity.TypeofDocument", "TypeofDocument")
                        .WithMany()
                        .HasForeignKey("TypeofDocumentId");
                });
#pragma warning restore 612, 618
        }
    }
}
