version: '3.4'

services:
  graphql:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44395
      - ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword"
#      - ASPNETCORE_Kestrel__Certificates__Development__Password="crypticpassword"
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=SampleDockerMVC.pfx
    ports:
      - "9000:80"
      - "44395:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro